CREATE TABLE IF NOT EXISTS CUSTOMER (
    ID_CUSTOMER NUMERIC SERIAL,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    COUNTRY_IDENTIFIER VARCHAR(100),
    PRIMARY KEY(ID_CUSTOMER)
);

CREATE TABLE IF NOT EXISTS BALANCE (
    ID_BALANCE NUMERIC SERIAL,
    BALANCE DECIMAL,
    ID_CUSTOMER NUMERIC,
    LAST_UPDATE TIMESTAMP,
    PRIMARY KEY(ID_BALANCE)
);
