CREATE TABLE IF NOT EXISTS category (id INTEGER IDENTITY PRIMARY KEY, name VARCHAR(100), description VARCHAR(2000), age_group VARCHAR(20), created DATETIME, inserted BIGINT);

CREATE TABLE IF NOT EXISTS Lego_Set (id INTEGER, name VARCHAR(100), min_Age INTEGER, max_Age INTEGER);
CREATE TABLE IF NOT EXISTS Handbuch (handbuch_id INTEGER, author VARCHAR(100), text CLOB);
CREATE TABLE IF NOT EXISTS Model (name VARCHAR(100), description CLOB, lego_set INTEGER);


-- The Brick aggregate
CREATE TABLE IF NOT EXISTS BRICK
(
  ID   BIGINT IDENTITY PRIMARY KEY ,
  DESCRIPTION VARCHAR(200)
);

-- The LegoModel aggregate
CREATE TABLE IF NOT EXISTS LEGO_MODEL
(
  ID   BIGINT IDENTITY PRIMARY KEY ,
  NAME VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS MANUAL
(
  LANGUAGE VARCHAR(10),
  CONTENT VARCHAR(2000),
  LEGO_MODEL BIGINT,
  LEGO_MODEL_KEY SMALLINT,
  PRIMARY KEY (LEGO_MODEL, LEGO_MODEL_KEY),
  FOREIGN KEY (LEGO_MODEL) REFERENCES LEGO_MODEL (ID)
);

CREATE TABLE IF NOT EXISTS CONTENT
(
    LEGO_MODEL BIGINT,
    BRICK_ID BIGINT,
    AMOUNT BIGINT,
    PRIMARY KEY (LEGO_MODEL, BRICK_ID),
    FOREIGN KEY (LEGO_MODEL) REFERENCES LEGO_MODEL (ID)
);
